In [1]:
import numpy as np

In [7]:
x = np.array([40,67,52,90,"A"])
print(x)
print(type(x))
print(x.dtype)

['40' '67' '52' '90' 'A']
<class 'numpy.ndarray'>
<U11


In [29]:
#Reshaping an array
a = np.arra([10,20,30,40])
b = a.reshape(2,2)
print(b)
print(b.shape)

AttributeError: module 'numpy' has no attribute 'arra'

In [13]:
a1 = np.array([3,4,5,8,7,2,8])
print(a1)
a1.dtype

[3 4 5 8 7 2 8]


dtype('int32')

In [15]:
a2 = np.array([[3,4,6],[7,9,10],[4,6,12]])
a2

array([[ 3,  4,  6],
       [ 7,  9, 10],
       [ 4,  6, 12]])

In [17]:
print(a2.sum(axis = 1))
print(a2.sum(axis=0))

[13 26 22]
[14 19 28]


In [19]:
print(a2)
print(np.mean(a2, axis =1))
print(np.mean(a2, axis =0))

[[ 3  4  6]
 [ 7  9 10]
 [ 4  6 12]]
[4.33333333 8.66666667 7.33333333]
[4.66666667 6.33333333 9.33333333]


In [23]:
a3 = np.array([[3,4,5],[7,2,8],[9,1,6]])
print(a3)
np.fill_diagonal(a3,0)
print(a3)

[[3 4 5]
 [7 2 8]
 [9 1 6]]
[[0 4 5]
 [7 0 8]
 [9 1 0]]


In [33]:
array([[3, 4, 5],
      [7, 2, 8],
      [9,1,6],
      [10, 9, 187]])
slice(1:3,0:2)

NameError: name 'array' is not defined